insert into genero values
(null, 'Pop'),
(null, 'Rock'),
(null, 'Rap'),
(null, 'Reggae'),
(null, 'Electronic'),
(null, 'Funk'),
(null, 'Heavy Metal'),
(null, 'Punk'),
(null, 'Indie'),
(null, 'MPB'),
(null, 'Jazz'),
(null, 'Soul');


insert into artista values 
(null, 'Linkin Park', 2),
(null, 'Michael Jackson', 1),
(null, 'Tupac', 3),
(null, 'Kendrick Lamar', 3),
(null, 'The weeknd', 5),
(null, 'Chance Atlantic', 9),
(null, 'Tyler, The creator', 3),
(null, 'Djonga', 3),
(null, 'BK', 3),
(null, 'L7nnon', 3),
(null, 'Nick Drake', 2),
(null, 'Benny Goodman', 11),
(null, 'The Velvet Underground', 2),
(null, 'Tim Maia', 12),
(null, 'Elis Regina & Tom Jobim', 10),
(null, 'Black Sabbath', 7),
(null, 'Miles Davis', 11),
(null, 'Blood, Sweat & Tears', 2),
(null, 'Nirvana', 2),
(null, 'Pixies', 9),
(null, 'Metallica', 7),
(null, 'Queen', 2),
(null, 'Red Hot Chili Peppers', 2),
(null, 'Daft Punk', 5),
(null, 'Rihanna', 1),
(null, 'Billie Eilish', 1),
(null, 'AC/DC', 2),
(null, 'Radiohead', 2),
(null, 'Foo Fighters', 2),
(null, 'Eminem', 3),
(null, 'Post Malone', 3),
(null, 'Bob Marley', 4),
(null, 'Adele', 1),
(null, 'Taylor Swift', 1),
(null, 'Coldplay', 2),
(null, 'Green Day', 7),
(null, 'Imagine Dragons', 1),
(null, 'Bruno Mars', 1),
(null, 'System of a Down', 2),
(null, 'The Beatles', 2),
(null, 'Pink Floyd', 2),
(null, 'The Rolling Stones', 2),
(null, 'Led Zeppelin', 2),
(null, 'Arctic Monkeys', 9),
(null, 'Blink-182', 7),
(null, 'Slipknot', 7),
(null, 'Gorillaz', 9),
(null, 'Pearl Jam', 2),
(null, 'Black Sabbath', 7),
(null, 'Skrillex', 2);
