insert into genero values
(null, 'Pop'),
(null, 'Rock'),
(null, 'Rap'),
(null, 'Reggae'),
(null, 'Electronic'),
(null, 'Funk'),
(null, 'Heavy Metal'),
(null, 'Punk'),
(null, 'Indie'),
(null, 'MPB'),
(null, 'Jazz'),
(null, 'Soul');


insert into artista values 
(null, 'Linkin Park', 2),
(null, 'Michael Jackson', 1),
(null, 'Tupac', 3),
(null, 'Kendrick Lamar', 3),
(null, 'The weeknd', 5),
(null, 'Chance Atlantic', 9),
(null, 'Tyler, The creator', 3),
(null, 'Djonga', 3),
(null, 'BK', 3),
(null, 'L7nnon', 3),
(null, 'Nick Drake', 2),
(null, 'Benny Goodman', 11),
(null, 'The Velvet Underground', 2),
(null, 'Tim Maia', 12),
(null, 'Elis Regina & Tom Jobim', 10),
(null, 'Black Sabbath', 7),
(null, 'Miles Davis', 11),
(null, 'Blood, Sweat & Tears', 2),
(null, 'Nirvana', 2),
(null, 'Pixies', 9),
(null, 'Metallica', 7),
(null, 'Queen', 2),
(null, 'Red Hot Chili Peppers', 2),
(null, 'Daft Punk', 5),
(null, 'Rihanna', 1),
(null, 'Billie Eilish', 1),
(null, 'AC/DC', 2),
(null, 'Radiohead', 2),
(null, 'Foo Fighters', 2),
(null, 'Eminem', 3),
(null, 'Post Malone', 3),
(null, 'Bob Marley', 4),
(null, 'Adele', 1),
(null, 'Taylor Swift', 1),
(null, 'Coldplay', 2),
(null, 'Green Day', 7),
(null, 'Imagine Dragons', 1),
(null, 'Bruno Mars', 1),
(null, 'System of a Down', 2),
(null, 'The Beatles', 2),
(null, 'Pink Floyd', 2),
(null, 'The Rolling Stones', 2),
(null, 'Led Zeppelin', 2),
(null, 'Arctic Monkeys', 9),
(null, 'Blink-182', 7),
(null, 'Slipknot', 7),
(null, 'Gorillaz', 9),
(null, 'Pearl Jam', 2),
(null, 'Black Sabbath', 7),
(null, 'Skrillex', 2);


insert into album values 
(null, 'Hybrid Theory', 2000, 1),
(null, 'Bad', 1987, 2),
(null, 'All Eyez on Me', 1996, 3),
(null, 'DAMN.', 2017, 4),
(null, 'Beauty Behind the Madness', 2015, 5),
(null, 'Chase Atlantic', 2017, 6),
(null, 'IGOR', 2019, 7),
(null, 'O Menino Que Queria Ser Deus', 2018, 8),
(null, 'Gigantes', 2018, 9),
(null, 'Podium', 2020, 10),
(null, 'Pink Moon', 1972, 11),
(null, 'The Famous 1938 Carnegie Hall Jazz Concert', 1938, 12),
(null, 'The Velvet Underground', 1969, 13),
(null, 'Álbum Branco', 1973, 14),
(null, 'Águas de Março', 1974, 15),
(null, 'Black Sabbath', 1970, 16),
(null, 'Kind of Blue', 1959, 17),
(null, 'Blood, Sweat & Tears', 1968, 18),
(null, 'Unplugged in New York', 1994, 19),
(null, 'Surfer Rosa', 1988, 20),
(null, 'Master of Puppets', 1986, 21),
(null, 'A Night at the Opera', 1975, 22),
(null, 'Californication', 1999, 23),
(null, 'Random Access Memories', 2013, 24),
(null, 'Anti', 2016, 25),
(null, 'When We All Fall Asleep, Where Do We Go?', 2019, 26),
(null, 'Back in Black', 1980, 27),
(null, 'OK Computer', 1997, 28),
(null, 'Wasting Light', 2011, 29),
(null, 'The Marshall Mathers LP', 2000, 30),
(null, 'Hollywoods Bleeding', 2019, 31),
(null, 'Legend', 1984, 32),
(null, '21', 2011, 33),
(null, '1989', 2014, 34),
(null, 'A Rush of Blood to the Head', 2002, 35),
(null, 'American Idiot', 2004, 36),
(null, 'Night Visions', 2012, 37),
(null, 'Doo-Wops & Hooligans', 2010, 38),
(null, 'Toxicity', 2001, 39),
(null, 'Abbey Road', 1969, 40),
(null, 'The Dark Side of the Moon', 1973, 41),
(null, 'Let It Bleed', 1969, 42),
(null, 'IV', 1971, 43),
(null, 'AM', 2013, 44),
(null, 'Enema of the State', 1999, 45),
(null, 'Slipknot', 2001, 46),
(null, 'Demon Days', 2005, 47),
(null, 'Ten', 1991, 48),
(null, 'Paranoid', 1970, 49),
(null, 'Recess', 2014, 50);

insert into compositor values 
(null, 'Linkin', 'Park'),
(null, 'Michael', 'Jackson'),
(null, 'Terry', 'Britten'),
(null, 'Siedah', 'Garrett'),
(null, 'Tupac', 'Shakur'),
(null, 'Kendrick', 'Lamar'),
(null, 'Abel', 'Tesfaye'),
(null, 'Chase', 'Atlantic'),
(null, 'Tyler', 'The Creator'),
(null, 'Djonga', null),
(null, 'BK', null),
(null, 'L7nnon', null),
(null, 'Nick', 'Drake'),
(null, 'Benny', 'Goodman'),
(null, 'The Velvet', 'Underground'),
(null, 'Tim', 'Maia'),
(null, 'Elis', 'Regina'),
(null, 'Black', 'Sabbath'),
(null, 'Miles', 'Davis'),
(null, 'Blood', 'Sweat & Tears'),
(null, 'Nirvana', null),
(null, 'Pixies', null),
(null, 'James', 'Hetfield'),
(null, 'Freddie', 'Mercury'),
(null, 'Brian', 'May'),
(null, 'Roger', 'Taylor'),
(null, 'John', 'Deacon'),
(null, 'Anthony', 'Kiedis'),
(null, 'Thomas', 'Bangalter'),
(null, 'Rihanna', null),
(null, 'Billie', 'Eilish'),
(null, 'Angus', 'Young'),
(null, 'Thom', 'Yorke'),
(null, 'Dave', 'Grohl'),
(null, 'Eminem', null),
(null, 'Post', 'Malone'),
(null, 'Bob', 'Marley'),
(null, 'Adele', null),
(null, 'Taylor', 'Swift'),
(null, 'Guy', 'Berryman'),
(null, 'Billie', 'Joe Armstrong'),
(null, 'Dan', 'Reynolds'),
(null, 'Bruno', 'Mars'),
(null, 'Serj', 'Tankian'),
(null, 'John', 'Lennon'), 
(null, 'George', 'Harrison'),
(null, 'Ringo', 'Starr'),
(null, 'Roger', 'Waters'),
(null, 'Mick', 'Jagger'),
(null, 'Jimmy', 'Page'), 
(null, 'Alex', 'Turner'),
(null, 'Mark', 'Hoppus'),
(null, 'Slipknot', null),
(null, 'Damon', 'Albarn'),
(null, 'Eddie', 'Vedder'),
(null, 'Ozzy', 'Osbourne'),
(null, 'Skrillex', null);
